import sys

give_str = sys.argv[1].lower()
print('A : ', give_str.count("a"))
print('B : ', give_str.count("b"))
print('C : ', give_str.count("c"))
print('D : ', give_str.count("d"))
print('E : ', give_str.count("e"))
print('F : ', give_str.count("f"))
print('G : ', give_str.count("g"))
print('H : ', give_str.count("h"))
print('I : ', give_str.count("i"))
print('J : ', give_str.count("j"))
print('K : ', give_str.count("k"))
print('L : ', give_str.count("l"))
print('M : ', give_str.count("m"))
print('N : ', give_str.count("n"))
print('O : ', give_str.count("o"))
print('P : ', give_str.count("p"))
print('Q : ', give_str.count("q"))
print('R : ', give_str.count("r"))
print('S : ', give_str.count("s"))
print('T : ', give_str.count("t"))
print('U : ', give_str.count("u"))
print('V : ', give_str.count("v"))
print('W : ', give_str.count("w"))
print('X : ', give_str.count("x"))
print('Y : ', give_str.count("y"))
print('Z : ', give_str.count("z"))

